#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5456
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="bbHome")]
	public partial class AccountDataSourceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBase_t_AccountDetail(Base_t_AccountDetail instance);
    partial void UpdateBase_t_AccountDetail(Base_t_AccountDetail instance);
    partial void DeleteBase_t_AccountDetail(Base_t_AccountDetail instance);
    partial void InsertBase_t_AccountSubject(Base_t_AccountSubject instance);
    partial void UpdateBase_t_AccountSubject(Base_t_AccountSubject instance);
    partial void DeleteBase_t_AccountSubject(Base_t_AccountSubject instance);
    partial void InsertBase_t_AccountInfo(Base_t_AccountInfo instance);
    partial void UpdateBase_t_AccountInfo(Base_t_AccountInfo instance);
    partial void DeleteBase_t_AccountInfo(Base_t_AccountInfo instance);
    partial void InsertBase_t_AccountAuditInfo(Base_t_AccountAuditInfo instance);
    partial void UpdateBase_t_AccountAuditInfo(Base_t_AccountAuditInfo instance);
    partial void DeleteBase_t_AccountAuditInfo(Base_t_AccountAuditInfo instance);
    partial void InsertBase_t_AccountScurityInfo(Base_t_AccountScurityInfo instance);
    partial void UpdateBase_t_AccountScurityInfo(Base_t_AccountScurityInfo instance);
    partial void DeleteBase_t_AccountScurityInfo(Base_t_AccountScurityInfo instance);
    #endregion
		
		public AccountDataSourceDataContext() : 
				base(global::Account.Data.Properties.Settings.Default.bbHomeConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public AccountDataSourceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountDataSourceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountDataSourceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountDataSourceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Base_t_AccountDetail> Base_t_AccountDetail
		{
			get
			{
				return this.GetTable<Base_t_AccountDetail>();
			}
		}
		
		public System.Data.Linq.Table<Base_t_AccountSubject> Base_t_AccountSubject
		{
			get
			{
				return this.GetTable<Base_t_AccountSubject>();
			}
		}
		
		public System.Data.Linq.Table<Base_t_AccountInfo> Base_t_AccountInfo
		{
			get
			{
				return this.GetTable<Base_t_AccountInfo>();
			}
		}
		
		public System.Data.Linq.Table<Base_t_AccountAuditInfo> Base_t_AccountAuditInfo
		{
			get
			{
				return this.GetTable<Base_t_AccountAuditInfo>();
			}
		}
		
		public System.Data.Linq.Table<Base_t_AccountScurityInfo> Base_t_AccountScurityInfo
		{
			get
			{
				return this.GetTable<Base_t_AccountScurityInfo>();
			}
		}
	}
	
	[Table(Name="dbo.Base_t_AccountDetail")]
	public partial class Base_t_AccountDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _accountId;
		
		private System.Nullable<int> _type;
		
		private string _orderid;
		
		private string _resume;
		
		private string _subjectCode;
		
		private System.Nullable<int> _custmerType;
		
		private string _custmerCode;
		
		private string _CustmerName;
		
		private System.Nullable<decimal> _useBalance;
		
		private System.Nullable<decimal> _endBalance;
		
		private System.Nullable<System.DateTime> _opTime;
		
		private string _opUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaccountIdChanging(System.Nullable<int> value);
    partial void OnaccountIdChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OnorderidChanging(string value);
    partial void OnorderidChanged();
    partial void OnresumeChanging(string value);
    partial void OnresumeChanged();
    partial void OnsubjectCodeChanging(string value);
    partial void OnsubjectCodeChanged();
    partial void OncustmerTypeChanging(System.Nullable<int> value);
    partial void OncustmerTypeChanged();
    partial void OncustmerCodeChanging(string value);
    partial void OncustmerCodeChanged();
    partial void OnCustmerNameChanging(string value);
    partial void OnCustmerNameChanged();
    partial void OnuseBalanceChanging(System.Nullable<decimal> value);
    partial void OnuseBalanceChanged();
    partial void OnendBalanceChanging(System.Nullable<decimal> value);
    partial void OnendBalanceChanged();
    partial void OnopTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnopTimeChanged();
    partial void OnopUserChanging(string value);
    partial void OnopUserChanged();
    #endregion
		
		public Base_t_AccountDetail()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_accountId", DbType="Int")]
		public System.Nullable<int> accountId
		{
			get
			{
				return this._accountId;
			}
			set
			{
				if ((this._accountId != value))
				{
					this.OnaccountIdChanging(value);
					this.SendPropertyChanging();
					this._accountId = value;
					this.SendPropertyChanged("accountId");
					this.OnaccountIdChanged();
				}
			}
		}
		
		[Column(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[Column(Storage="_orderid", DbType="VarChar(20)")]
		public string orderid
		{
			get
			{
				return this._orderid;
			}
			set
			{
				if ((this._orderid != value))
				{
					this.OnorderidChanging(value);
					this.SendPropertyChanging();
					this._orderid = value;
					this.SendPropertyChanged("orderid");
					this.OnorderidChanged();
				}
			}
		}
		
		[Column(Storage="_resume", DbType="VarChar(50)")]
		public string resume
		{
			get
			{
				return this._resume;
			}
			set
			{
				if ((this._resume != value))
				{
					this.OnresumeChanging(value);
					this.SendPropertyChanging();
					this._resume = value;
					this.SendPropertyChanged("resume");
					this.OnresumeChanged();
				}
			}
		}
		
		[Column(Storage="_subjectCode", DbType="VarChar(50)")]
		public string subjectCode
		{
			get
			{
				return this._subjectCode;
			}
			set
			{
				if ((this._subjectCode != value))
				{
					this.OnsubjectCodeChanging(value);
					this.SendPropertyChanging();
					this._subjectCode = value;
					this.SendPropertyChanged("subjectCode");
					this.OnsubjectCodeChanged();
				}
			}
		}
		
		[Column(Storage="_custmerType", DbType="Int")]
		public System.Nullable<int> custmerType
		{
			get
			{
				return this._custmerType;
			}
			set
			{
				if ((this._custmerType != value))
				{
					this.OncustmerTypeChanging(value);
					this.SendPropertyChanging();
					this._custmerType = value;
					this.SendPropertyChanged("custmerType");
					this.OncustmerTypeChanged();
				}
			}
		}
		
		[Column(Storage="_custmerCode", DbType="VarChar(50)")]
		public string custmerCode
		{
			get
			{
				return this._custmerCode;
			}
			set
			{
				if ((this._custmerCode != value))
				{
					this.OncustmerCodeChanging(value);
					this.SendPropertyChanging();
					this._custmerCode = value;
					this.SendPropertyChanged("custmerCode");
					this.OncustmerCodeChanged();
				}
			}
		}
		
		[Column(Storage="_CustmerName", DbType="VarChar(50)")]
		public string CustmerName
		{
			get
			{
				return this._CustmerName;
			}
			set
			{
				if ((this._CustmerName != value))
				{
					this.OnCustmerNameChanging(value);
					this.SendPropertyChanging();
					this._CustmerName = value;
					this.SendPropertyChanged("CustmerName");
					this.OnCustmerNameChanged();
				}
			}
		}
		
		[Column(Storage="_useBalance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> useBalance
		{
			get
			{
				return this._useBalance;
			}
			set
			{
				if ((this._useBalance != value))
				{
					this.OnuseBalanceChanging(value);
					this.SendPropertyChanging();
					this._useBalance = value;
					this.SendPropertyChanged("useBalance");
					this.OnuseBalanceChanged();
				}
			}
		}
		
		[Column(Storage="_endBalance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> endBalance
		{
			get
			{
				return this._endBalance;
			}
			set
			{
				if ((this._endBalance != value))
				{
					this.OnendBalanceChanging(value);
					this.SendPropertyChanging();
					this._endBalance = value;
					this.SendPropertyChanged("endBalance");
					this.OnendBalanceChanged();
				}
			}
		}
		
		[Column(Storage="_opTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> opTime
		{
			get
			{
				return this._opTime;
			}
			set
			{
				if ((this._opTime != value))
				{
					this.OnopTimeChanging(value);
					this.SendPropertyChanging();
					this._opTime = value;
					this.SendPropertyChanged("opTime");
					this.OnopTimeChanged();
				}
			}
		}
		
		[Column(Storage="_opUser", DbType="VarChar(50)")]
		public string opUser
		{
			get
			{
				return this._opUser;
			}
			set
			{
				if ((this._opUser != value))
				{
					this.OnopUserChanging(value);
					this.SendPropertyChanging();
					this._opUser = value;
					this.SendPropertyChanged("opUser");
					this.OnopUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Base_t_AccountSubject")]
	public partial class Base_t_AccountSubject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _subjectType;
		
		private string _subjectName;
		
		private string _subjectCode;
		
		private string _direction;
		
		private System.Nullable<int> _parentId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsubjectTypeChanging(System.Nullable<int> value);
    partial void OnsubjectTypeChanged();
    partial void OnsubjectNameChanging(string value);
    partial void OnsubjectNameChanged();
    partial void OnsubjectCodeChanging(string value);
    partial void OnsubjectCodeChanged();
    partial void OndirectionChanging(string value);
    partial void OndirectionChanged();
    partial void OnparentIdChanging(System.Nullable<int> value);
    partial void OnparentIdChanged();
    #endregion
		
		public Base_t_AccountSubject()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_subjectType", DbType="Int")]
		public System.Nullable<int> subjectType
		{
			get
			{
				return this._subjectType;
			}
			set
			{
				if ((this._subjectType != value))
				{
					this.OnsubjectTypeChanging(value);
					this.SendPropertyChanging();
					this._subjectType = value;
					this.SendPropertyChanged("subjectType");
					this.OnsubjectTypeChanged();
				}
			}
		}
		
		[Column(Storage="_subjectName", DbType="VarChar(50)")]
		public string subjectName
		{
			get
			{
				return this._subjectName;
			}
			set
			{
				if ((this._subjectName != value))
				{
					this.OnsubjectNameChanging(value);
					this.SendPropertyChanging();
					this._subjectName = value;
					this.SendPropertyChanged("subjectName");
					this.OnsubjectNameChanged();
				}
			}
		}
		
		[Column(Storage="_subjectCode", DbType="VarChar(50)")]
		public string subjectCode
		{
			get
			{
				return this._subjectCode;
			}
			set
			{
				if ((this._subjectCode != value))
				{
					this.OnsubjectCodeChanging(value);
					this.SendPropertyChanging();
					this._subjectCode = value;
					this.SendPropertyChanged("subjectCode");
					this.OnsubjectCodeChanged();
				}
			}
		}
		
		[Column(Storage="_direction", DbType="VarChar(1000)")]
		public string direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[Column(Storage="_parentId", DbType="Int")]
		public System.Nullable<int> parentId
		{
			get
			{
				return this._parentId;
			}
			set
			{
				if ((this._parentId != value))
				{
					this.OnparentIdChanging(value);
					this.SendPropertyChanging();
					this._parentId = value;
					this.SendPropertyChanged("parentId");
					this.OnparentIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Base_t_AccountInfo")]
	public partial class Base_t_AccountInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _userType;
		
		private string _userId;
		
		private System.Nullable<decimal> _balance;
		
		private System.Nullable<int> _status;
		
		private string _accCode;
		
		private System.Nullable<decimal> _blockBalance;
		
		private System.Nullable<System.DateTime> _createTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuserTypeChanging(System.Nullable<int> value);
    partial void OnuserTypeChanged();
    partial void OnuserIdChanging(string value);
    partial void OnuserIdChanged();
    partial void OnbalanceChanging(System.Nullable<decimal> value);
    partial void OnbalanceChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnaccCodeChanging(string value);
    partial void OnaccCodeChanged();
    partial void OnblockBalanceChanging(System.Nullable<decimal> value);
    partial void OnblockBalanceChanged();
    partial void OncreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreateTimeChanged();
    #endregion
		
		public Base_t_AccountInfo()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_userType", DbType="Int")]
		public System.Nullable<int> userType
		{
			get
			{
				return this._userType;
			}
			set
			{
				if ((this._userType != value))
				{
					this.OnuserTypeChanging(value);
					this.SendPropertyChanging();
					this._userType = value;
					this.SendPropertyChanged("userType");
					this.OnuserTypeChanged();
				}
			}
		}
		
		[Column(Storage="_userId", DbType="VarChar(50)")]
		public string userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[Column(Storage="_balance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[Column(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[Column(Storage="_accCode", DbType="VarChar(50)")]
		public string accCode
		{
			get
			{
				return this._accCode;
			}
			set
			{
				if ((this._accCode != value))
				{
					this.OnaccCodeChanging(value);
					this.SendPropertyChanging();
					this._accCode = value;
					this.SendPropertyChanged("accCode");
					this.OnaccCodeChanged();
				}
			}
		}
		
		[Column(Storage="_blockBalance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> blockBalance
		{
			get
			{
				return this._blockBalance;
			}
			set
			{
				if ((this._blockBalance != value))
				{
					this.OnblockBalanceChanging(value);
					this.SendPropertyChanging();
					this._blockBalance = value;
					this.SendPropertyChanged("blockBalance");
					this.OnblockBalanceChanged();
				}
			}
		}
		
		[Column(Storage="_createTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> createTime
		{
			get
			{
				return this._createTime;
			}
			set
			{
				if ((this._createTime != value))
				{
					this.OncreateTimeChanging(value);
					this.SendPropertyChanging();
					this._createTime = value;
					this.SendPropertyChanged("createTime");
					this.OncreateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Base_t_AccountAuditInfo")]
	public partial class Base_t_AccountAuditInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _accountId;
		
		private System.Nullable<int> _type;
		
		private string _direction;
		
		private string _subjectCode;
		
		private string _refId;
		
		private System.Nullable<decimal> _opBalance;
		
		private System.Nullable<bool> _status;
		
		private System.Nullable<System.DateTime> _createTime;
		
		private System.Nullable<System.DateTime> _opTime;
		
		private string _opUser;
		
		private string _remark;
		
		private string _createUser;
		
		private System.Nullable<int> _custmerType;
		
		private string _custmerCode;
		
		private string _custmerName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaccountIdChanging(System.Nullable<int> value);
    partial void OnaccountIdChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OndirectionChanging(string value);
    partial void OndirectionChanged();
    partial void OnsubjectCodeChanging(string value);
    partial void OnsubjectCodeChanged();
    partial void OnrefIdChanging(string value);
    partial void OnrefIdChanged();
    partial void OnopBalanceChanging(System.Nullable<decimal> value);
    partial void OnopBalanceChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    partial void OncreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreateTimeChanged();
    partial void OnopTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnopTimeChanged();
    partial void OnopUserChanging(string value);
    partial void OnopUserChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OncreateUserChanging(string value);
    partial void OncreateUserChanged();
    partial void OncustmerTypeChanging(System.Nullable<int> value);
    partial void OncustmerTypeChanged();
    partial void OncustmerCodeChanging(string value);
    partial void OncustmerCodeChanged();
    partial void OncustmerNameChanging(string value);
    partial void OncustmerNameChanged();
    #endregion
		
		public Base_t_AccountAuditInfo()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_accountId", DbType="Int")]
		public System.Nullable<int> accountId
		{
			get
			{
				return this._accountId;
			}
			set
			{
				if ((this._accountId != value))
				{
					this.OnaccountIdChanging(value);
					this.SendPropertyChanging();
					this._accountId = value;
					this.SendPropertyChanged("accountId");
					this.OnaccountIdChanged();
				}
			}
		}
		
		[Column(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[Column(Storage="_direction", DbType="VarChar(100)")]
		public string direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[Column(Storage="_subjectCode", DbType="VarChar(50)")]
		public string subjectCode
		{
			get
			{
				return this._subjectCode;
			}
			set
			{
				if ((this._subjectCode != value))
				{
					this.OnsubjectCodeChanging(value);
					this.SendPropertyChanging();
					this._subjectCode = value;
					this.SendPropertyChanged("subjectCode");
					this.OnsubjectCodeChanged();
				}
			}
		}
		
		[Column(Storage="_refId", DbType="VarChar(20)")]
		public string refId
		{
			get
			{
				return this._refId;
			}
			set
			{
				if ((this._refId != value))
				{
					this.OnrefIdChanging(value);
					this.SendPropertyChanging();
					this._refId = value;
					this.SendPropertyChanged("refId");
					this.OnrefIdChanged();
				}
			}
		}
		
		[Column(Storage="_opBalance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> opBalance
		{
			get
			{
				return this._opBalance;
			}
			set
			{
				if ((this._opBalance != value))
				{
					this.OnopBalanceChanging(value);
					this.SendPropertyChanging();
					this._opBalance = value;
					this.SendPropertyChanged("opBalance");
					this.OnopBalanceChanged();
				}
			}
		}
		
		[Column(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[Column(Storage="_createTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> createTime
		{
			get
			{
				return this._createTime;
			}
			set
			{
				if ((this._createTime != value))
				{
					this.OncreateTimeChanging(value);
					this.SendPropertyChanging();
					this._createTime = value;
					this.SendPropertyChanged("createTime");
					this.OncreateTimeChanged();
				}
			}
		}
		
		[Column(Storage="_opTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> opTime
		{
			get
			{
				return this._opTime;
			}
			set
			{
				if ((this._opTime != value))
				{
					this.OnopTimeChanging(value);
					this.SendPropertyChanging();
					this._opTime = value;
					this.SendPropertyChanged("opTime");
					this.OnopTimeChanged();
				}
			}
		}
		
		[Column(Storage="_opUser", DbType="VarChar(50)")]
		public string opUser
		{
			get
			{
				return this._opUser;
			}
			set
			{
				if ((this._opUser != value))
				{
					this.OnopUserChanging(value);
					this.SendPropertyChanging();
					this._opUser = value;
					this.SendPropertyChanged("opUser");
					this.OnopUserChanged();
				}
			}
		}
		
		[Column(Storage="_remark", DbType="VarChar(500)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[Column(Storage="_createUser", DbType="VarChar(50)")]
		public string createUser
		{
			get
			{
				return this._createUser;
			}
			set
			{
				if ((this._createUser != value))
				{
					this.OncreateUserChanging(value);
					this.SendPropertyChanging();
					this._createUser = value;
					this.SendPropertyChanged("createUser");
					this.OncreateUserChanged();
				}
			}
		}
		
		[Column(Storage="_custmerType", DbType="Int")]
		public System.Nullable<int> custmerType
		{
			get
			{
				return this._custmerType;
			}
			set
			{
				if ((this._custmerType != value))
				{
					this.OncustmerTypeChanging(value);
					this.SendPropertyChanging();
					this._custmerType = value;
					this.SendPropertyChanged("custmerType");
					this.OncustmerTypeChanged();
				}
			}
		}
		
		[Column(Storage="_custmerCode", DbType="VarChar(50)")]
		public string custmerCode
		{
			get
			{
				return this._custmerCode;
			}
			set
			{
				if ((this._custmerCode != value))
				{
					this.OncustmerCodeChanging(value);
					this.SendPropertyChanging();
					this._custmerCode = value;
					this.SendPropertyChanged("custmerCode");
					this.OncustmerCodeChanged();
				}
			}
		}
		
		[Column(Storage="_custmerName", DbType="VarChar(50)")]
		public string custmerName
		{
			get
			{
				return this._custmerName;
			}
			set
			{
				if ((this._custmerName != value))
				{
					this.OncustmerNameChanging(value);
					this.SendPropertyChanging();
					this._custmerName = value;
					this.SendPropertyChanged("custmerName");
					this.OncustmerNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Base_t_AccountScurityInfo")]
	public partial class Base_t_AccountScurityInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _accountId;
		
		private string _payPassword;
		
		private System.Nullable<int> _useNumber;
		
		private string _scurityEmail;
		
		private string _scurityTel;
		
		private System.Nullable<bool> _isUseEmail;
		
		private System.Nullable<bool> _isUseTel;
		
		private System.Nullable<bool> _isChangePwd;
		
		private System.Nullable<System.DateTime> _createTime;
		
		private string _emailValidateCode;
		
		private string _telValidateCode;
		
		private System.Nullable<System.DateTime> _emailExpirationTime;
		
		private System.Nullable<System.DateTime> _telExpirationTime;
		
		private string _waitUpdateScurityEmail;
		
		private string _waitUpdateScurityTel;
		
		private string _pwdKey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaccountIdChanging(System.Nullable<int> value);
    partial void OnaccountIdChanged();
    partial void OnpayPasswordChanging(string value);
    partial void OnpayPasswordChanged();
    partial void OnuseNumberChanging(System.Nullable<int> value);
    partial void OnuseNumberChanged();
    partial void OnscurityEmailChanging(string value);
    partial void OnscurityEmailChanged();
    partial void OnscurityTelChanging(string value);
    partial void OnscurityTelChanged();
    partial void OnisUseEmailChanging(System.Nullable<bool> value);
    partial void OnisUseEmailChanged();
    partial void OnisUseTelChanging(System.Nullable<bool> value);
    partial void OnisUseTelChanged();
    partial void OnisChangePwdChanging(System.Nullable<bool> value);
    partial void OnisChangePwdChanged();
    partial void OncreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreateTimeChanged();
    partial void OnemailValidateCodeChanging(string value);
    partial void OnemailValidateCodeChanged();
    partial void OntelValidateCodeChanging(string value);
    partial void OntelValidateCodeChanged();
    partial void OnemailExpirationTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnemailExpirationTimeChanged();
    partial void OntelExpirationTimeChanging(System.Nullable<System.DateTime> value);
    partial void OntelExpirationTimeChanged();
    partial void OnwaitUpdateScurityEmailChanging(string value);
    partial void OnwaitUpdateScurityEmailChanged();
    partial void OnwaitUpdateScurityTelChanging(string value);
    partial void OnwaitUpdateScurityTelChanged();
    partial void OnpwdKeyChanging(string value);
    partial void OnpwdKeyChanged();
    #endregion
		
		public Base_t_AccountScurityInfo()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_accountId", DbType="Int")]
		public System.Nullable<int> accountId
		{
			get
			{
				return this._accountId;
			}
			set
			{
				if ((this._accountId != value))
				{
					this.OnaccountIdChanging(value);
					this.SendPropertyChanging();
					this._accountId = value;
					this.SendPropertyChanged("accountId");
					this.OnaccountIdChanged();
				}
			}
		}
		
		[Column(Storage="_payPassword", DbType="VarChar(128)")]
		public string payPassword
		{
			get
			{
				return this._payPassword;
			}
			set
			{
				if ((this._payPassword != value))
				{
					this.OnpayPasswordChanging(value);
					this.SendPropertyChanging();
					this._payPassword = value;
					this.SendPropertyChanged("payPassword");
					this.OnpayPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_useNumber", DbType="Int")]
		public System.Nullable<int> useNumber
		{
			get
			{
				return this._useNumber;
			}
			set
			{
				if ((this._useNumber != value))
				{
					this.OnuseNumberChanging(value);
					this.SendPropertyChanging();
					this._useNumber = value;
					this.SendPropertyChanged("useNumber");
					this.OnuseNumberChanged();
				}
			}
		}
		
		[Column(Storage="_scurityEmail", DbType="VarChar(100)")]
		public string scurityEmail
		{
			get
			{
				return this._scurityEmail;
			}
			set
			{
				if ((this._scurityEmail != value))
				{
					this.OnscurityEmailChanging(value);
					this.SendPropertyChanging();
					this._scurityEmail = value;
					this.SendPropertyChanged("scurityEmail");
					this.OnscurityEmailChanged();
				}
			}
		}
		
		[Column(Storage="_scurityTel", DbType="VarChar(20)")]
		public string scurityTel
		{
			get
			{
				return this._scurityTel;
			}
			set
			{
				if ((this._scurityTel != value))
				{
					this.OnscurityTelChanging(value);
					this.SendPropertyChanging();
					this._scurityTel = value;
					this.SendPropertyChanged("scurityTel");
					this.OnscurityTelChanged();
				}
			}
		}
		
		[Column(Storage="_isUseEmail", DbType="Bit")]
		public System.Nullable<bool> isUseEmail
		{
			get
			{
				return this._isUseEmail;
			}
			set
			{
				if ((this._isUseEmail != value))
				{
					this.OnisUseEmailChanging(value);
					this.SendPropertyChanging();
					this._isUseEmail = value;
					this.SendPropertyChanged("isUseEmail");
					this.OnisUseEmailChanged();
				}
			}
		}
		
		[Column(Storage="_isUseTel", DbType="Bit")]
		public System.Nullable<bool> isUseTel
		{
			get
			{
				return this._isUseTel;
			}
			set
			{
				if ((this._isUseTel != value))
				{
					this.OnisUseTelChanging(value);
					this.SendPropertyChanging();
					this._isUseTel = value;
					this.SendPropertyChanged("isUseTel");
					this.OnisUseTelChanged();
				}
			}
		}
		
		[Column(Storage="_isChangePwd", DbType="Bit")]
		public System.Nullable<bool> isChangePwd
		{
			get
			{
				return this._isChangePwd;
			}
			set
			{
				if ((this._isChangePwd != value))
				{
					this.OnisChangePwdChanging(value);
					this.SendPropertyChanging();
					this._isChangePwd = value;
					this.SendPropertyChanged("isChangePwd");
					this.OnisChangePwdChanged();
				}
			}
		}
		
		[Column(Storage="_createTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> createTime
		{
			get
			{
				return this._createTime;
			}
			set
			{
				if ((this._createTime != value))
				{
					this.OncreateTimeChanging(value);
					this.SendPropertyChanging();
					this._createTime = value;
					this.SendPropertyChanged("createTime");
					this.OncreateTimeChanged();
				}
			}
		}
		
		[Column(Storage="_emailValidateCode", DbType="VarChar(60)")]
		public string emailValidateCode
		{
			get
			{
				return this._emailValidateCode;
			}
			set
			{
				if ((this._emailValidateCode != value))
				{
					this.OnemailValidateCodeChanging(value);
					this.SendPropertyChanging();
					this._emailValidateCode = value;
					this.SendPropertyChanged("emailValidateCode");
					this.OnemailValidateCodeChanged();
				}
			}
		}
		
		[Column(Storage="_telValidateCode", DbType="VarChar(20)")]
		public string telValidateCode
		{
			get
			{
				return this._telValidateCode;
			}
			set
			{
				if ((this._telValidateCode != value))
				{
					this.OntelValidateCodeChanging(value);
					this.SendPropertyChanging();
					this._telValidateCode = value;
					this.SendPropertyChanged("telValidateCode");
					this.OntelValidateCodeChanged();
				}
			}
		}
		
		[Column(Storage="_emailExpirationTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> emailExpirationTime
		{
			get
			{
				return this._emailExpirationTime;
			}
			set
			{
				if ((this._emailExpirationTime != value))
				{
					this.OnemailExpirationTimeChanging(value);
					this.SendPropertyChanging();
					this._emailExpirationTime = value;
					this.SendPropertyChanged("emailExpirationTime");
					this.OnemailExpirationTimeChanged();
				}
			}
		}
		
		[Column(Storage="_telExpirationTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> telExpirationTime
		{
			get
			{
				return this._telExpirationTime;
			}
			set
			{
				if ((this._telExpirationTime != value))
				{
					this.OntelExpirationTimeChanging(value);
					this.SendPropertyChanging();
					this._telExpirationTime = value;
					this.SendPropertyChanged("telExpirationTime");
					this.OntelExpirationTimeChanged();
				}
			}
		}
		
		[Column(Storage="_waitUpdateScurityEmail", DbType="VarChar(50)")]
		public string waitUpdateScurityEmail
		{
			get
			{
				return this._waitUpdateScurityEmail;
			}
			set
			{
				if ((this._waitUpdateScurityEmail != value))
				{
					this.OnwaitUpdateScurityEmailChanging(value);
					this.SendPropertyChanging();
					this._waitUpdateScurityEmail = value;
					this.SendPropertyChanged("waitUpdateScurityEmail");
					this.OnwaitUpdateScurityEmailChanged();
				}
			}
		}
		
		[Column(Storage="_waitUpdateScurityTel", DbType="VarChar(20)")]
		public string waitUpdateScurityTel
		{
			get
			{
				return this._waitUpdateScurityTel;
			}
			set
			{
				if ((this._waitUpdateScurityTel != value))
				{
					this.OnwaitUpdateScurityTelChanging(value);
					this.SendPropertyChanging();
					this._waitUpdateScurityTel = value;
					this.SendPropertyChanged("waitUpdateScurityTel");
					this.OnwaitUpdateScurityTelChanged();
				}
			}
		}
		
		[Column(Storage="_pwdKey", DbType="VarChar(50)")]
		public string pwdKey
		{
			get
			{
				return this._pwdKey;
			}
			set
			{
				if ((this._pwdKey != value))
				{
					this.OnpwdKeyChanging(value);
					this.SendPropertyChanging();
					this._pwdKey = value;
					this.SendPropertyChanged("pwdKey");
					this.OnpwdKeyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
